Homework_5
MastersAcademy/ruby-rails-course pull request #235
Opened 2016-12-08 09:35 UTC by serjpetrenko

2016-12-09 21:29 UTC, skoddowl commented on homeworks/serhiy.petrenko_serjpetrenko/Homework_5/Hometask_5.rb
> +module Ingredients_classic
Тут и дальше используй для названий классов и модулей `CamelCase`. (https://github.com/bbatsov/ruby-style-guide#camelcase-classes)

2016-12-09 21:29 UTC, skoddowl commented on homeworks/serhiy.petrenko_serjpetrenko/Homework_5/Hometask_5.rb
> +  attr_accessor :set
Зачем accessor для set? Я не вижу такой переменной экземпляра.

2016-12-09 21:29 UTC, skoddowl commented on homeworks/serhiy.petrenko_serjpetrenko/Homework_5/Hometask_5.rb
> +    @ingredients_classic = Ingredients_classic
`@ingredients_classic` нигде не используется.

2016-12-09 21:29 UTC, skoddowl commented on homeworks/serhiy.petrenko_serjpetrenko/Homework_5/Hometask_5.rb
> +      case choice
Тут можно было сделать намного проще. Создать хеш в котором ключи это возможный выбор юзера (1, 2, 3 и т.д.), а значения тоже хеши с ключами имя (коктейля) и рецепт:
```
cocktails = { 
  1 => { name: 'Mojito', recipe: 'White rum - 50 ml,\nlime - 2 slices,\nmint - 15 gr.,\nsimple syrup - 20 gr.' },
  2 => { name: 'Cuba libre', recipe: 'Black rum - 50 ml\nCola - 150 ml\nFresh lime juice - 10 ml' }
} 
```
Тогда намного проще делать выборку по коктейлям:
```
choice = gets.to_i
cocktail = cocktails[choice]
```
И уже дальше работать с переменной `cocktail`. Мне кажется что может получиться в 2 раза меньше кода.

Перепиши этот модуль и модуль `New_era` используя эту идею.

2016-12-09 21:30 UTC, skoddowl requested changes
Исправь ошибки и добавь пример с extend.

2016-12-10 11:55 UTC, serjpetrenko commented
Дуже дякую вам за допомогу!)

2016-12-15 13:49 UTC, closed without merging