homework_5
MastersAcademy/ruby-rails-course pull request #237
Opened 2016-12-08 16:48 UTC by dmitriy-sanitskiy

2016-12-09 21:47 UTC, skoddowl commented on homeworks/dmitriy.sanitskiy_dmitriy-sanitskiy/homework_5/1.rb
> +  40.times { print "+'=" }
В данном случае это запускается на 2й строчке твоего файла, а не на 72й, не вижу смысла оформлять такой "функционал" в виде отдельного модуля и его екстендить.

2016-12-09 21:47 UTC, skoddowl commented on homeworks/dmitriy.sanitskiy_dmitriy-sanitskiy/homework_5/1.rb
> +  def add_article(article)
А у статьи нельзя узнать список категорий?

2016-12-09 21:48 UTC, skoddowl commented on homeworks/dmitriy.sanitskiy_dmitriy-sanitskiy/homework_5/1.rb
> +class ArticleClass
Старайся не добавлять `Class` в конец названия класса, это плохая практика.

2016-12-09 21:48 UTC, skoddowl commented on homeworks/dmitriy.sanitskiy_dmitriy-sanitskiy/homework_5/1.rb
> +  include Category
Ну обычно модули используются чтобы расширить существующий функционал класса, а ты положил всю реализацию классов в модули и просто их заинклудил. Немного похоже на читерство. Расширь функционал своих классов и сделай так чтобы весь функционал не лежал в одном модуле.

2016-12-09 21:48 UTC, skoddowl requested changes
Исправь мелкие недочеты, расширь функционал своих классов и сделай так чтобы весь функционал не лежал в одном модуле.

2016-12-12 11:44 UTC, dmitriy-sanitskiy commented on homeworks/dmitriy.sanitskiy_dmitriy-sanitskiy/homework_5/1.rb
> +  def add_article(article)
category has_many articles
article belong_to category

2016-12-15 13:49 UTC, closed without merging