Homework 6.
MastersAcademy/ruby-rails-course pull request #283
Opened 2016-12-18 16:45 UTC by simplewayUA

2016-12-19 11:12 UTC, skoddowl commented on homeworks/dima.olefir_simplewayUA/homework_5_6/objects,classes,exceptions.rb
> +    $id_card = id_card
Зачем тут глобальные переменные? Они не только тут не нужны, но ещё и ломают твою программу.

2016-12-19 11:12 UTC, skoddowl commented on homeworks/dima.olefir_simplewayUA/homework_5_6/objects,classes,exceptions.rb
> +class StatementError < StandardError
Это неправильное определение эксепшна.
```
class MyError < StandardError
  def initialize(msg="My default message")
    super
  end
end
```

2016-12-19 11:13 UTC, skoddowl commented
Избавься от глобальных переменных, исправь ошибки. Не вижу задания 1 из домашки 6.

2016-12-19 11:25 UTC, skoddowl requested changes
Избавься от глобальных переменных, исправь ошибки. Не вижу задания 1 из домашки 6.

2016-12-20 20:27 UTC, simplewayUA commented
@skoddowl Исправил, пойдут изменения?

2017-01-16 15:38 UTC, closed without merging