Homework_6.rb
MastersAcademy/ruby-rails-course pull request #285
Opened 2016-12-18 18:32 UTC by rizon0503

my homework 6

2016-12-19 11:18 UTC, skoddowl commented on homeworks/viacheslav.otamas_rizon0503/Homework-6/Homework_6.rb
> +class MyError < StandardError
Это неправильное определение эксепшна.
```
class MyError < StandardError
  def initialize(msg="My default message")
    super
  end
end
```

2016-12-19 11:18 UTC, skoddowl commented on homeworks/viacheslav.otamas_rizon0503/Homework-6/Homework_6.rb
> +            puts 'You have chosen the best credit line! ;-)'
Неправильные отступы

2016-12-19 11:18 UTC, skoddowl commented on homeworks/viacheslav.otamas_rizon0503/Homework-6/Homework_6.rb
> +class BuilderCreditProgramCar
Зачем этот класс? Почему не сделать этот функционал в конструкторе или на крайний случай в отдельном методе? Зачем столько лишних методов и строчек кода?

2016-12-19 11:18 UTC, skoddowl commented on homeworks/viacheslav.otamas_rizon0503/Homework-6/Homework_6.rb
> +class BuilderCreditProgramHome
Зачем этот класс? Почему не сделать этот функционал в конструкторе или на крайний случай в отдельном методе? Зачем столько лишних методов и строчек кода?

2016-12-19 11:18 UTC, skoddowl commented on homeworks/viacheslav.otamas_rizon0503/Homework-6/Homework_6.rb
> +    credit_currency, credit_period, credit_rate, secured_loan,
Лучше разбить эту часть на несколько строк.

2016-12-19 11:18 UTC, skoddowl commented on homeworks/viacheslav.otamas_rizon0503/Homework-6/Homework_6.rb
> +  attr_accessor :credit_currency,
Такое оформление занимает очень много места, лучше написать это в 2 строчки

2016-12-19 11:19 UTC, skoddowl commented on homeworks/viacheslav.otamas_rizon0503/Homework-6/Homework_6.rb
> +  def construct_credit_program
Очень много лишних строчек, не в стиле Руби :)

2016-12-19 11:20 UTC, skoddowl requested changes
По функционалу ок, но нужно исправить недочеты.

2016-12-19 15:08 UTC, rizon0503 commented
Перевірте, будь-ласка, вже вніс зміни.

2016-12-19 16:15 UTC, skoddowl requested changes
Очень тяжело читать такие конструкции как у тебя. Оформи свои классы подобно этому:
```
class CreditProgram
  attr_accessor :credit_currency, :credit_period, :credit_rate, :secured_loan,
                :in_cash, :foreign_currency, :credit_program_name

  def initialize(credit_currency = 0, credit_period = 0, credit_rate = 0,
                 secured_loan = false, in_cash = false, foreign_currency = false,
                 credit_program_name = "Def")

    @credit_currency = credit_currency
    @credit_period = credit_period
    @credit_rate = credit_rate
    @secured_loan = secured_loan
    @in_cash = in_cash
    @foreign_currency = foreign_currency,
    @credit_program_name = credit_program_name
  end
end
```

2016-12-19 16:16 UTC, skoddowl commented
И вообще старайся не писать методы в которых больше 4х параметров. Всегда можно сделать проще.

2016-12-19 16:47 UTC, rizon0503 commented
Оформив класи. Буду старатися слідувати рекомендаціям.

2016-12-20 11:22 UTC, rizon0503 commented
Переробив деякі методи

2016-12-26 16:11 UTC, skoddowl commented on homeworks/viacheslav.otamas_rizon0503/Homework-6/Homework_6.rb
> +class MyError < StandardError
Название ошибки должно иметь какой-то смысл. С её названия любой другой разработчик должен понимать какая именно это ошибка и в каких случаях она возникает.

2016-12-26 16:15 UTC, merged

2016-12-27 08:35 UTC, rizon0503 commented on homeworks/viacheslav.otamas_rizon0503/Homework-6/Homework_6.rb
> +class MyError < StandardError
Врахую це зауваження. Дякую.