hw_5_fix
MastersAcademy/ruby-rails-course pull request #290
Opened 2016-12-18 21:21 UTC by Ripchanskiy

2016-12-19 10:21 UTC, skoddowl commented
Нет задания с эксепшнами

2016-12-19 11:27 UTC, skoddowl requested changes
Нет задания с эксепшнами

2016-12-24 19:54 UTC, Ripchanskiy commented
Готово!

2016-12-26 16:16 UTC, skoddowl commented on homeworks/sergey.ripchanskiy_Ripchanskiy/homework 5/HW5_6.rb
> +    rescue NoMethodError => e
В этом блоке код оформлен не по стайлгайду. 4 пробела вместо 2 и скобки в вызове метода без аргументов

2016-12-26 16:18 UTC, skoddowl commented on homeworks/sergey.ripchanskiy_Ripchanskiy/homework 5/HW5_6.rb
> +    if @verification == true
Тут тоже отступы неправильные

2016-12-26 16:18 UTC, merged