Homework 8
MastersAcademy/ruby-rails-course pull request #319
Opened 2017-01-21 16:21 UTC by shuforov

1 bundler install
2 rake start
3 http://localhost:4567/

Постараюсь выложить еще на heroku.

2017-01-23 13:21 UTC, skoddowl commented on homeworks/oleg.monastyretsky_shuforov/Homework_8/app.rb
> +  @@users = User.all.map {|user| user.name}
Почему `@@users` это переменная класса? + Обычно если переменная называется `users` то ожидается что там будет массив пользователей, а не массив имён пользователей.

2017-01-23 13:21 UTC, skoddowl commented on homeworks/oleg.monastyretsky_shuforov/Homework_8/app.rb
> +  if params[:user_name].length <= 0 or @@users.include?(params[:user_name])
Почитай про [валидации в ActiveRecord](http://guides.rubyonrails.org/active_record_validations.html)

2017-01-23 13:21 UTC, skoddowl commented on homeworks/oleg.monastyretsky_shuforov/Homework_8/app.rb
> +  @all_users = User.all
Принято называть переменные просто `@users`, а не `@all_users` и т.д.

2017-01-23 13:21 UTC, skoddowl commented on homeworks/oleg.monastyretsky_shuforov/Homework_8/app.rb
> +  @user_id = User.find_by_name(params['name']).id
Тут лучше было достать все посты юзера через объект юзера:
```
@user = User.find_by_name(params[:name])
@posts = @user.posts
```
Почитать больше: http://guides.rubyonrails.org/association_basics.html

2017-01-23 13:21 UTC, skoddowl commented on homeworks/oleg.monastyretsky_shuforov/Homework_8/app.rb
> +  Post.where(id: @@post_id).update(title: params[:title_name])
Тут лучше было сделать так:
```
@post = Post.find(params[:post_id])
@post.update_attributes(title: params[:title_name], body: params[:body_name])
```
И добавить чтобы в параметрах передавался айди поста:
```
get '/posts/:id/edit' do
```
И в других ендпойнтах так же.

2017-01-23 13:22 UTC, skoddowl commented on homeworks/oleg.monastyretsky_shuforov/Homework_8/models/user.rb
> +  has_many :posts
При удалении юзера также должны удаляться его посты.

2017-01-25 09:10 UTC, skoddowl commented on homeworks/oleg.monastyretsky_shuforov/Homework_8/app.rb
> +get '/posts/new/:id' do
`/users/:id/posts/new`

2017-01-25 09:10 UTC, skoddowl commented on homeworks/oleg.monastyretsky_shuforov/Homework_8/app.rb
> +get '/posts/show/:id' do
По такой урле непонятно что параметр айди это айди юзера. В этом случае урла должна быть `/users/:id/posts`

2017-01-25 09:11 UTC, skoddowl requested changes
Перечитай http://guides.rubyonrails.org/routing.html и поправь урлы

2017-01-25 13:45 UTC, Mnilko commented
Жду домашку с RSpec и исправлениями

2017-01-25 13:45 UTC, closed without merging