Homework 6, 7
MastersAcademy/ruby-rails-course pull request #325
Opened 2017-01-25 14:46 UTC by simplewayUA

Почистил пул https://goo.gl/KhDJB1

2017-01-28 11:32 UTC, simplewayUA commented
Add **homework 8.1**

2017-01-30 11:25 UTC, skoddowl commented on homeworks/dima.olefir_simplewayUA/homework_8.1/sinatra_example/app.rb
> +    @author = User.find_by_id(@post.user_id)
Вместо этого можно было `@author = @post.user`.

2017-01-30 11:25 UTC, skoddowl commented on homeworks/dima.olefir_simplewayUA/homework_8.1/sinatra_example/app.rb
> +    @post.user_id = params[:user_id]
Тут и дальше можно делать так `@post = Post.new(user_id: params[:user_id])`

2017-01-30 11:25 UTC, skoddowl commented on homeworks/dima.olefir_simplewayUA/homework_8.1/sinatra_example/app.rb
> +  post '/users/:user_id/posts/create' do
По соглашениям урла должна быть `POST /users/:user_id/posts`, `create` тут лишний.

2017-01-30 11:25 UTC, skoddowl commented on homeworks/dima.olefir_simplewayUA/homework_8.1/sinatra_example/app.rb
> +  get '/posts/:id/delete' do
Удаление объектов должно делаться http методом `DELETE`

2017-01-30 11:25 UTC, skoddowl requested changes
Нормальная домашка, но перечитай http://guides.rubyonrails.org/active_record_basics.htm, http://guides.rubyonrails.org/association_basics.html и http://guides.rubyonrails.org/routing.html. Обрати внимание на то какие методы тебе предоставляет ActiveRecord. Маловато тестов, нет тестирования ендпоинтов.

2017-02-05 12:28 UTC, simplewayUA commented
[Rails example]: https://intense-oasis-78708.herokuapp.com

2017-02-05 12:32 UTC, simplewayUA commented
[Rails example](https://intense-oasis-78708.herokuapp.com)

2017-02-06 15:30 UTC, merged