Homework 8.1 with rspec tests
MastersAcademy/ruby-rails-course pull request #330
Opened 2017-01-29 16:35 UTC by serjpetrenko

Added changes to code and wrote tests with rspec
Link to github repository https://github.com/serjpetrenko/sinatra-simple-blog
Link to heroku: https://quiet-ocean-17544.herokuapp.com

2017-01-30 12:18 UTC, skoddowl commented on homeworks/serhiy.petrenko_serjpetrenko/Homework_8.1/app.rb
> +get '/users.json' do
На прошлой лекции Валик говорил не писать по два ендпоинта отдельно на джейсон и хтмл, а использовать гем https://github.com/cehoffman/sinatra-respond_to

2017-01-30 12:18 UTC, skoddowl commented on homeworks/serhiy.petrenko_serjpetrenko/Homework_8.1/app.rb
> +  @user = User.new
`@user = User.new(name: params[:username])`

2017-01-30 12:18 UTC, skoddowl commented on homeworks/serhiy.petrenko_serjpetrenko/Homework_8.1/app.rb
> +get '/users/:id/delete' do
Удаление объектов должно делаться http методом DELETE

2017-01-30 12:18 UTC, skoddowl commented on homeworks/serhiy.petrenko_serjpetrenko/Homework_8.1/app.rb
> +get '/users/:id/posts/create' do
`create` тут лишний + создание поста не должно делаться методом GET, это должно делаться методом POST

2017-01-30 12:18 UTC, skoddowl commented on homeworks/serhiy.petrenko_serjpetrenko/Homework_8.1/app.rb
> +  @user = User.find(params[:id])
А где тут создание поста?

2017-01-30 12:18 UTC, skoddowl commented on homeworks/serhiy.petrenko_serjpetrenko/Homework_8.1/app.rb
> +  @user_id = Post.find(params[:post_id]).user_id
Лучше было сделать так:
```
@post = Post.find(params[:post_id])
@post.destroy
redirect "/users/#{@post.user_id}"
```

2017-01-30 12:19 UTC, skoddowl requested changes
Перечитай http://guides.rubyonrails.org/active_record_basics.htm, http://guides.rubyonrails.org/association_basics.html и http://guides.rubyonrails.org/routing.html. Обрати внимание на то какие методы тебе предоставляет ActiveRecord.

2017-01-31 22:51 UTC, serjpetrenko commented on homeworks/serhiy.petrenko_serjpetrenko/Homework_8.1/app.rb
> +get '/users/:id/posts/create' do
Просто в цьому випадку завантажується форма зі створенням посту, наступним в коді йде метод POST зі створенням посту, якщо критично буду старатись переробити.

2017-02-01 08:54 UTC, skoddowl commented on homeworks/serhiy.petrenko_serjpetrenko/Homework_8.1/app.rb
> +get '/users/:id/posts/create' do
Якщо це форма стоврення поста, то це має бути `get '/users/:id/posts/new`

2017-02-06 15:32 UTC, merged